kind: pipeline
type: docker
name: default

steps:
  - name: ssh commands
    image: appleboy/drone-ssh:1.5.5
    settings:
      host: 157.230.43.114
      username: ci
      password: edu
      port: 22
      script:
        - mkdir test
