kind: pipeline
type: ssh
name: default

server:
  host: 157.230.43.114
  user: ci
  password: edu

steps:
  - name: build
    image: node:latest
    commands:
      - mkdir test2
      - pwd
      - touch test.txt
      - ls
