kind: pipeline
name: default

steps:
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host: 157.230.43.114
      username: ci
      key: ${SSH_KEY}
      script:
        - echo "hello there"
